
import "./globals.css";
import { Poppins } from "next/font/google";
import { ClientLayout } from "./clientlayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Select desired font weights
  variable: "--font-poppins", // Set CSS variable for Tailwind
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased overflow-x-hidden ${poppins.className}`}
      >
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
